# Generated by Django 2.1.5 on 2019-01-16 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shout',
            table='"shouts"',
        ),
    ]
