# Generated by Django 2.1.5 on 2019-01-17 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shout',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shouts.User'),
        ),
    ]
