# Generated by Django 2.1.5 on 2019-01-18 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shouts', '0002_shout_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shout',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shouts', to='shouts.User'),
        ),
    ]
